### ISSUE TITLE
[PE-D][Tester E] Hint command not working when numbers are added as questions

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-4/tp#170]
![Screenshot 2023-11-03 at 4.49.29 PM.png](https://raw.githubusercontent.com/techjay-c/ped/main/files/4bbcd26d-2972-4420-9e18-67b0219dc850.png)
When numbers are added as questions, eg question 3 in the screenshot, the hint command (hint "123455"), where 123455 is the question name, does not work. Allows addition of flashcard questions as numbers, but the hint command does not work for such questions

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: techjay-c/ped#10

**Comment by Dioclei** [comment]
Not a bug. The `hint` command does not take in full questions as parameters. As per the user guide, the `hint` command only takes in an index (referring to the position of the question in the list), not the question itself, i.e. `hint INDEX`.

Hence, in this bug report, the command in question, i.e. `hint 123455`, will attempt to obtain the hint of the question at index `123455`, which is invalid because there is no question at position `123455`. In order to obtain the hint for question 3. 123455, `hint 3` will work.
